theme: jekyll-theme-minimal
title: home
url: //centre-for-virus-research.github.io
baseurl: "/CVR-VBG-2023"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
kramdown:
  input: GFM
  syntax_highlighter: rouge
