remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: CVR-VBG-2023
logo: /assets/img/logo.png
url: //centre-for-virus-research.github.io
baseurl: "/CVR-VBG-2023"
color-scheme: light
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
kramdown:
  input: GFM
  syntax_highlighter: rouge
favicon: true
include:
  - README.md
  - Introduction_to_Linux.md
  - Read Cleaning.md
  - ReferenceAlignment.md
  - Phylogenetics.md
  - De Novo Practicals.md
  - QualityAssessment.md
  - Metagenomics.md
  - KmerMetagenomics.md
  - Transcriptomics.md


platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/centre-for-virus-research
