remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: CVR-VBG-2023
logo: /assets/img/logo.png
url: //centre-for-virus-research.github.io
baseurl: "/CVR-VBG-2023"
color-scheme: light
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
favicon: true
navigation:
title: Modules
  - name: About
    link: ./index.html
  - name: Introduction to Linux
    link: ./Introduction_to_Linux.html
  - name: Read Cleaning
    link: ./ReadCleaning.html
  - name: ReferenceAlignment
    link: ./ReferenceAlignment.html
  - name: Phylogenetics
    link: ./Phylogenetics.html
  - name: De Novo Practicals
    link: ./DeNovoPracticals.html
  - name: QualityAssessment
    link: ./QualityAssessment.html
  - name: Metagenomics
    link: ./Metagenomics.html
  - name: KmerMetagenomics
    link: ./KmerMetagenomics.html
  - name: Transcriptomics
    link: ./Transcriptomics.html
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3  
platforms:
  - name: GitHub page of CVR
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/centre-for-virus-research
