theme: jekyll-theme-minimal
logo: /assets/img/logo.png
title: home
url: //centre-for-virus-research.github.io
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
kramdown:
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
  math_engine: mathjax
  syntax_highlighter: rouge
include:
  - README.md
  - Introduction_to_Linux.md
  - Read Cleaning.md
  - ReferenceAlignment.md
  - Phylogenetics.md
  - De Novo Practicals.md
  - QualityAssessment.md
  - Metagenomics.md
  - KmerMetagenomics.md
  - Transcriptomics.md
