remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: CVR-VBG-2023
logo: /assets/img/logo.png
url: //centre-for-virus-research.github.io
baseurl: "/CVR-VBG-2023"
color-scheme: light
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
favicon: true
include:
  - README.md
  - Introduction_to_Linux.md
  - Read Cleaning.md
  - ReferenceAlignment.md
  - Phylogenetics.md
  - De Novo Practicals.md
  - QualityAssessment.md
  - Metagenomics.md
  - KmerMetagenomics.md
  - Transcriptomics.md

navigation:
  - name: About
    link: ./about.html
  - name: Introduction to Linux
    link: ./Introduction_to_Linux.html
  - name: Read Cleaning
    link: ./Read%20Cleaning.html`
  - name: ReferenceAlignment
    link: ./ReferenceAlignment.html
  - name: Phylogenetics
    link: ./Phylogenetics.html
  - name: De Novo Practicals
    link: ./De%20Novo%20Practicals.html`
  - name: QualityAssessment
    link: ./QualityAssessment.html
  - name: Metagenomics
    link: ./Metagenomics.html
  - name: KmerMetagenomics
    link: ./KmerMetagenomics.html
  - name: Transcriptomics
    link: ./Transcriptomics.html
    
    
  
platforms:
  - name: GitHub page of CVR Bioinformatics
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/centre-for-virus-research
