plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Introduction_to_Linux.Rmd
  - Read Cleaning.md
  - ./ReferenceAlignment.html
  - Phylogenetics.md
  - De Novo Practicals.md
  - QualityAssessment.md
  - Metagenomics.md
  - KmerMetagenomics.md
  - Transcriptomics.md
