---
title: "Introduction to Linux"
author: "Srikeerthana Kuchi"
#date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 4
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
div.blue pre { background-color:lightblue; }
div.red pre { background-color:red; }

</style>

<style type="text/css">
body{font-size: 14pt;}
</style>

> **Color codes** \
> <font color='blue'>Text in Blue – Refer “Info” section</font> \
> <font color='magenta'>Text in Pink – Points to remember</font> \
> <mark style="background-color: lightblue">Text background in lightblue - commands </mark> \
> <mark style="background-color: Grey">Text background in Grey – Command output </mark> \
> <mark style="background-color: Red">Text background in Red – Alert/Warning </mark> \


## Introduction

<font color='blue'>Linux</font> is an open-source operating system <font color='blue'>OS</font> developed based on the kernel created by Linus Benedict Torvalds. In the last two decades, Linux has gained much popularity and now is being used on many platforms. Nowadays, most of the high-end servers to mobile phones (Android OS or iOS) run on different variants of Linux.

Linux computers/servers are installed for multi-user usage. In this course, we will work on a virtual machine (<font color='blue'>VM</font>) running (<font color='blue'>Ubuntu</font>) desktop edition. Most of the commands specified in this manual can be used in any other distribution (i.e., CentOS, Debian, etc.) of Linux operating system. 

#### Resource: How to install Ubuntu?

To install Ubuntu on personal computers, please follow the instructions in the following link.
[Install Ubuntu](https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-desktop#0)

#### The Terminal 

We use terminal (AKA command line interface) to interact with the operating system. The terminal by default runs one of the “shells”. Shell is a program that sits between the user and the <font color='blue'>kernel</font> and translates user commands (text) into machine code. The advantages of using command line are greater control and flexibility over the system or software and multiple commands can be saved in a file and executed as a program.

The most common shells are:
 
Bourne Shell \
Bourne Again Shell – BASH (variant is Z Shell) \
C Shell (variant is T Shell) \
K Shell \

Among these Bourne Again Shell (BASH) is the most popular one. This is the default shell on the system, and we will be using it throughout this course. 

#### Connecting to Linux Server

In this course, we will be using MobaXterm application to access the OS of a server version of Ubuntu. Please use the provided username and password to login into your account.

> Open MobaXterm -> Sessions -> New session -> <font color='blue'>ssh</font> -> add remote host and username -> OK -> Enter password -> Don't save password

#### Linux command structure 

When you open a terminal in Linux, (MobaXterm by default opens a terminal), you will see a command prompt, ready to take commands. The default location on the terminal is your “home directory”. It is represented with ~ (tilde) symbol.

Copy the command below and paste it into your command line to copy the contents of the directory Linux to your home directory.

<div class = "blue">
```{bash, eval=F, echo =T}
cp -R /home4/VBG_data/Linux .
```
</div>

All Linux commands are single words (can be alpha-numeric), with optional parameters followed by arguments. For historical reasons, some of the early commands are only two letter long and case sensitive. Most of the command options (also called flags) are single letters. They should be speci-fied after the command before giving any input. 

<div class = "blue">
```{bash, eval=F, echo =T}
ls -l Linux
```
</div>

"ls" is the command to list the contents of the directory, "-l" is the option for long listing and "Linux" is the input, which is optional in this case. Without the input, "ls" shows the contents of the current directory (Type <mark style="background-color: lightblue">ls -l</mark>). 

<font color='magenta'>
Points to remember: \

> •	Linux commands are case sensitive and are always single words \
> •	Options follow the command - and they start with a single hyphen (-) and a character or a double hyphen (- -) and a word \
> •	Single character options can be combined \
> •	Argument can be one or two inputs \
> •	You can write more than one command separating with a semicolon; You can use “tab” to auto-fill the command \

</font>

#### First Commands

Directories are the Unix equivalent of folders on a <font color='blue'>PC</font> or a <font color='blue'>Mac</font>. They are organized in a hierarchy, so directories can have sub-directories and so on. Directories, like folders, are useful to keep your data files organized. The location or directory you are currently in, is called the current working directory. The location or “full pathname” of the file SARS-CoV-2.fa in the 'Linux' directory can be expressed as: 

```
/home_location/username/Linux
```

#### Tab completion

Typing out longer file names can be boring, and you are likely to make typos that will, at best, make your command fail with a strange error and at worst, overwrite some of your carefully crafted analysis. 

Tab completion is a trick that normally reduces this risk significantly. Instead of typing out "ls Interesting_stuff/", try typing “ls Int” and press the Tab button (instead of Enter). The rest of the folder/file names that begin with “Int” should be listed. If you have two folders/files with similar names (e.g., my_awesome_scripts/ and my_awesome_results/) then you might need to give your terminal a bit of a hand to work out which one you want. In this case if you type "ls –l m", when you press Tab the terminal would read "ls –l my_awesome_". You could then type "s" followed by another press of Tab button and it would figure out that you meant "my_awesome_scripts/".

#### <span style="text-decoration:underline">Info</span>
<font color='blue'>

|   Terminology | Description                                                                               |
|---------------|-------------------------------------------------------------------------------------------|
|   Linux       |Unix derivative, most popular variant of Unix                                              |
|   OS          |Software that commands the hardware and make the computer work                             |
|   VM          |A resource that can run an OS independent of the host OS (e.g., Ubuntu VM on a Mac OS)     |
|   Ubuntu      |Free Linux distribution (distro) based on Debian (an oldest OS based on Linux kernel)      |
|   Kernel      |Core interface between a computer’s hardware and its processes, manages available resources|
|   ssh         |Program for logging in to a remote machine specified with a host name                      |
|   PC          |A personal computer                                                                        |
|   Mac         |A Macintosh computer                                                                       |

</font>


## Important Linux Commands

*(a)* ls \
Lists information about the files/directories. Default is the current directory. Sorts entries alphabetically. \

Commonly used options: \
-l long list \
-a show all files (including hidden files) \
-t sort based on last modified time \

<div class = "blue">
```{bash, eval=F, echo =T}
ls -l
```
</div>

Information (from left to right): \
•	File permissions \
•	Number of links \
•	Owner name \
•	Group name \
•	Number of bytes \
•	Abbreviated month, last modified date and time \
•	File/Directory name \

*(b)* pwd \
Returns the path of the current working directory (print working directory) to the standard output. \

<div class = "blue">
```{bash, eval=F, echo =T}
pwd
```
</div>

*(c)* cd \
Change current working directory to the specified directory. \

<div class = "blue">
```{bash, eval=F, echo =T}
cd Exercises/
pwd
```
</div>

We are now in the directory "Exercises". Typing the command "cd .." changes it to the parent directory from which the previous command was typed in. Typing "cd" will change the current directory to the home directory.

<div class = "blue">
```{bash, eval=F, echo =T}
cd
cd Linux/
```
</div>

*(d)* mkdir \
This command creates a directory in the current working directory if no file/directory exists with the specified name. \

<div class = "blue">
```{bash, eval=F, echo =T}
mkdir Practice
ls -l
```
</div>

*(e)* rmdir \
This command is used to remove directories. \

<div class = "blue">
```{bash, eval=F, echo =T}
rmdir Practice
ls -l
```
</div>

*(f)* touch \
It is file’s time-stamp changing command. However, it can be used to create an empty file. This command is generally used to check if there is write permission for the current user.

<div class = "blue">
```{bash, eval=F, echo =T}
touch temp-file
ls -l
```
</div>

*(g)* rm \
rm is used for removing files and directories.

<div class = "blue">
```{bash, eval=F, echo =T}
rm temp-file
ls -l
```
</div>


<div class = "red">
```
To remove directories use "-r" option. Please remember once a file or directory is deleted, it will not go to "Recycle bin" in Linux and there is no way you can recover it. 
```
</div>

*(h)* cp \
 Copies the content of the source file/directory to the target file/directory. To copy directories, use "-r" option.
 
<div class = "blue">
```{bash, eval=F, echo =T}
touch temp1
cp temp1 temp2
ls -l
```
</div>

*(i)* mv
To move/rename a file or a directory.

<div class = "blue">
```{bash, eval=F, echo =T}
mkdir temp
mv temp1 temp/.
mv temp2 temp3
ls -l
```
</div>

The second command moves the "temp1" file into the directory "temp". The "." (dot) at the end of the command retains the name of the file, whereas the third command renames the file "temp2" to "temp3".

*(j)* ln
Link command is used to make links to files/directories. We encourage you to create links rather than copying data in order to save space.

<div class = "blue">
```{bash, eval=F, echo =T}
ln -s temp/temp1 .
ls -l 
```
</div>









